#ifndef KUONMENU_H
#define KUONMENU_H

enum _KUON_MENU__RELOAD_FLAG_EN {
    KUON_MENU_RELOAD_FLAG_NONE = 0,
    KUON_MENU_RELOAD_FLAG_TITLE_ = 1,
    KUON_MENU_RELOAD_FLAG_START = 2,
    KUON_MENU_RELOAD_FLAG_MAIN = 4,
    KUON_MENU_RELOAD_FLAG_SAVE = 8,
    KUON_MENU_RELOAD_FLAG_LOAD = 16,
    KUON_MENU_RELOAD_FLAG_DEAD = 32,
    KUON_MENU_RELOAD_FLAG_MM_TOP = 64,
    KUON_MENU_RELOAD_FLAG_MM_EQUIP = 128,
    KUON_MENU_RELOAD_FLAG_MM_ITEM = 256,
    KUON_MENU_RELOAD_FLAG_MM_BOOK = 512,
    KUON_MENU_RELOAD_FLAG_MM_MAP = 1024,
    KUON_MENU_RELOAD_FLAG_MM_SET = 2048,
    KUON_MENU_RELOAD_FLAG_MM_END = 4096,
    KUON_MENU_RELOAD_FLAG_DOC = 8192,
    KUON_MENU_RELOAD_FLAG_GAME = 16384,
    KUON_MENU_RELOAD_FLAG_TITLE = -32768,
};

int KnMenuMng_Update(int call_check /* r16 */);
int KnMenuMng_Draw();
int KnMenuMng_Crean();

#endif // KUONMENU_H
