#ifndef MENU_H
#define MENU_H

enum _KUON_MENU__TYPE_EN {
    KUON_MENU__TEST_MENU = 0,
    KUON_MENU__TITLE_MENU = 1,
    KUON_MENU__START_MENU = 2,
    KUON_MENU__MAIN_MENU = 3,
    KUON_MENU__SAVE_MENU = 4,
    KUON_MENU__LOAD_MENU = 5,
    KUON_MENU__MAP_MENU = 6,
    KUON_MENU__ITEM_MENU = 7,
    KUON_MENU__MSG_MENU = 8,
    KUON_MENU__SET_MENU = 9,
    KUON_MENU__END_SAVE_MENU = 10,
    KUON_MENU__DEAD_MENU = 11,
    KUON_MENU__MENU_NUM = 12,
    KUON_MENU__MAKE_NONE = 100,
    KUON_MENU__MAKE_TITLE = 101,
    KUON_MENU__MAKE_GAME = 102,
    KUON_MENU__DMY_MENU = 999,
};




#endif // MENU_H
